# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  displayName: Prepare SonarCloud analysis
  inputs:
    SonarCloud: 'sonarcloud-markcmoore'
    organization: 'markcmoore-revature'
    scannerMode: 'MSBuild'
    projectKey: 'markcmoore-project1'
    extraProperties: |
        sonar.exclusions=**/lib/**

- script: dotnet build Project1-Mark/Project1-Mark.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
#   workingDirectory: ./testToWork

# a task can encapsulate some useful logic so we don't have to
# write it all out in script step...
# in this case, this task is both running tests and publishing the results
# to the build itself
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './testToWork'
    arguments: '-c $(buildConfiguration) --collect "XPlat Code Coverage"'

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: SonarCloudAnalyze@1
  displayName: Run SonarCloud analysis

- task: SonarCloudPublish@1
  displayName: Publish SonarCloud quality gate result

- task: DotNetCoreCLI@2
  displayName: dotnet publish + zip
  inputs:
    command: 'publish'
    arguments: --configuration $(buildConfiguration)
    projects: ./testToWork
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  displayName: App Service deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(386f8ffa-3367-4bd7-b850-f755512189e6)'
    appType: 'webApp'
    WebAppName: 'project1-mark'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'